"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import SuggestedTools from "@/components/SuggestedTools";
import GlassBadge from "@/components/GlassBadge";

export default function DesignTokensClient() {
  const [primaryColor, setPrimaryColor] = useState("#FF5B04");
  const [baseFont, setBaseFont] = useState("Inter");
  const [borderRadius, setBorderRadius] = useState("16");
  const [copied, setCopied] = useState(false);

  const tailwindConfig = `// tailwind.config.js - Generated by UI Pirate
module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          50: "${primaryColor}15",
          100: "${primaryColor}30",
          500: "${primaryColor}",
          600: "${primaryColor}E6",
          900: "${primaryColor}CC",
        },
        surface: {
          light: "#FAFAFA",
          card: "#FFFFFF",
          border: "#E5E7EB",
          dark: "#0F0F11",
        }
      },
      borderRadius: {
        'brand': '${borderRadius}px',
      },
      fontFamily: {
        sans: ['${baseFont}', 'sans-serif'],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      }
    }
  }
};`;

  const copyCode = () => {
    navigator.clipboard.writeText(tailwindConfig);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#FAFAFA] relative overflow-hidden">
      {/* Background Grid & Ambient Glow */}
      <div
        className="absolute inset-0 pointer-events-none -top-10"
        style={{
          backgroundImage: `
            linear-gradient(to right, rgba(0, 0, 0, 0.04) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(0, 0, 0, 0.04) 1px, transparent 1px)
          `,
          backgroundSize: "40px 40px",
          maskImage: "radial-gradient(ellipse at 50% 25%, black 40%, transparent 80%)",
          WebkitMaskImage: "radial-gradient(ellipse at 50% 25%, black 40%, transparent 80%)",
        }}
      />
      <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[700px] h-[340px] bg-[#FF5B04]/10 blur-[140px] rounded-full pointer-events-none -z-10" />

      <div className="container mx-auto px-32 lg:px-20 max-md:px-4 pt-32 pb-20 relative z-10">
        {/* Hero */}
        <motion.div
          initial={{ opacity: 0, y: -12 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12 max-w-4xl mx-auto"
        >
          <div className="mb-6 flex flex-row items-center justify-center">
            <GlassBadge variant="gradient">DESIGN SYSTEMS &amp; TOKENS</GlassBadge>
          </div>

          <h1 className="text-[38px] sm:text-[50px] md:text-[62px] lg:text-[70px] text-center font-[800] tracking-[-1.5px] leading-[1.08] text-gray-900 mb-5">
            SaaS Design Token &amp; <span className="text-[#FF5B04]">Tailwind</span> Generator
          </h1>
          <p className="text-base sm:text-lg text-gray-500 max-w-2xl mx-auto text-center font-normal leading-relaxed">
            Generate production-ready design tokens, 8pt spacing scales, typography ramps, and Tailwind CSS config objects in seconds.
          </p>
        </motion.div>

        {/* Builder Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 max-w-5xl mx-auto">
          {/* Controls */}
          <div className="lg:col-span-5 bg-white border border-gray-200 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
            <h3 className="text-sm font-bold text-gray-900 font-jakarta uppercase tracking-wider">
              Token Parameters
            </h3>

            <div>
              <label className="block text-xs font-semibold text-gray-700 mb-2">Primary Brand Color</label>
              <div className="flex items-center gap-3">
                <input
                  type="color"
                  value={primaryColor}
                  onChange={(e) => setPrimaryColor(e.target.value)}
                  className="w-10 h-10 rounded-xl cursor-pointer border border-gray-200"
                />
                <input
                  type="text"
                  value={primaryColor}
                  onChange={(e) => setPrimaryColor(e.target.value)}
                  className="px-3 py-2 border border-gray-200 rounded-xl text-xs font-mono text-gray-800 uppercase outline-none"
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-700 mb-2">Base Typography Font</label>
              <select
                value={baseFont}
                onChange={(e) => setBaseFont(e.target.value)}
                className="w-full px-3.5 py-2.5 border border-gray-200 rounded-xl text-xs text-gray-800 outline-none bg-white font-jakarta"
              >
                <option value="Inter">Inter (SaaS Default)</option>
                <option value="Plus Jakarta Sans">Plus Jakarta Sans (Modern Clean)</option>
                <option value="Geist">Geist (Developer-First)</option>
                <option value="Outfit">Outfit (Punchy & Bold)</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-700 mb-2">
                Card & Button Border Radius: <span className="font-mono text-[#FF5B04]">{borderRadius}px</span>
              </label>
              <input
                type="range"
                min="0"
                max="32"
                value={borderRadius}
                onChange={(e) => setBorderRadius(e.target.value)}
                className="w-full accent-[#FF5B04]"
              />
            </div>

            <div className="pt-4 border-t border-gray-100">
              <Link
                href="/contact"
                className="block text-center px-4 py-3 rounded-2xl bg-gray-900 hover:bg-black text-white text-xs font-bold transition-all shadow-sm"
              >
                Need a Custom Enterprise Design System? →
              </Link>
            </div>
          </div>

          {/* Code Output */}
          <div className="lg:col-span-7 bg-white border border-gray-200 rounded-3xl p-6 sm:p-8 shadow-sm flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-bold text-gray-900 uppercase tracking-wider font-mono">
                  tailwind.config.js
                </span>
                <button
                  onClick={copyCode}
                  className="px-3.5 py-1.5 rounded-xl bg-[#FF5B04] hover:bg-[#E54F00] text-white text-xs font-bold transition-all flex items-center gap-1.5 shadow-sm shadow-[#FF5B04]/15 cursor-pointer"
                >
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  {copied ? "Copied to Clipboard!" : "Copy Config"}
                </button>
              </div>

              <pre className="p-4 rounded-2xl bg-gray-900 text-emerald-400 font-mono text-xs overflow-x-auto leading-relaxed max-h-[380px]">
                {tailwindConfig}
              </pre>
            </div>
          </div>
        </div>

        {/* Detailed Landing Page Content / Educational Guide */}
        <section className="mt-24 pt-14 border-t border-gray-200 max-w-5xl mx-auto space-y-16">
          <div className="text-center max-w-3xl mx-auto">
            <span className="text-[11px] font-mono font-bold uppercase tracking-wider text-[#FF5B04]">
              Design System Engineering
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 font-jakarta mt-2">
              The Building Blocks of Production Design Systems
            </h2>
            <p className="text-xs text-gray-500 mt-2 leading-relaxed">
              Design tokens bridge the gap between Figma design systems and front-end engineering, maintaining visual consistency across large SaaS applications.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white border border-gray-200 rounded-3xl p-6 shadow-sm">
              <span className="text-2xl font-bold font-mono text-[#FF5B04] mb-3 block">01</span>
              <h3 className="text-sm font-bold text-gray-900 mb-2 font-jakarta">8-Point Spacing Grid</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                Standardizing margins, paddings, and component heights on an 8pt scale eliminates visual guesswork and ensures pixel-perfect layout alignment.
              </p>
            </div>

            <div className="bg-white border border-gray-200 rounded-3xl p-6 shadow-sm">
              <span className="text-2xl font-bold font-mono text-[#FF5B04] mb-3 block">02</span>
              <h3 className="text-sm font-bold text-gray-900 mb-2 font-jakarta">Tailwind Config Tokens</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                Exporting semantic color variables (<code className="font-mono text-gray-800">brand-500</code>, <code className="font-mono text-gray-800">surface-card</code>) enables instant light/dark theme switching with zero runtime CSS overhead.
              </p>
            </div>

            <div className="bg-white border border-gray-200 rounded-3xl p-6 shadow-sm">
              <span className="text-2xl font-bold font-mono text-[#FF5B04] mb-3 block">03</span>
              <h3 className="text-sm font-bold text-gray-900 mb-2 font-jakarta">Typography Ramps</h3>
              <p className="text-xs text-gray-500 leading-relaxed">
                Consistent typographic scale ratios (Minor Third vs Perfect Fourth) keep dashboard headers and table data cleanly proportioned.
              </p>
            </div>
          </div>

          {/* FAQs */}
          <div className="bg-white border border-gray-200 rounded-3xl p-6 sm:p-10 shadow-sm">
            <h3 className="text-xl font-bold text-gray-900 font-jakarta mb-6">
              Frequently Asked Questions about Design Tokens
            </h3>
            <div className="space-y-4">
              <div className="p-4 rounded-2xl bg-gray-50 border border-gray-100">
                <h4 className="text-xs font-bold text-gray-900 mb-1">What are design tokens?</h4>
                <p className="text-xs text-gray-600 leading-relaxed">
                  Design tokens are the atomic visual design values (colors, typography, spacing, border radii) stored as platform-agnostic variables that both Figma and code consume.
                </p>
              </div>
              <div className="p-4 rounded-2xl bg-gray-50 border border-gray-100">
                <h4 className="text-xs font-bold text-gray-900 mb-1">How do I integrate this with Tailwind CSS?</h4>
                <p className="text-xs text-gray-600 leading-relaxed">
                  Copy the generated configuration object directly into the <code className="font-mono text-gray-800">theme.extend</code> block of your <code className="font-mono text-gray-800">tailwind.config.js</code> or <code className="font-mono text-gray-800">tailwind.config.ts</code> file.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Suggested Tools */}
        <SuggestedTools currentToolId="design-tokens" category="design-system" />
      </div>
    </div>
  );
}
