// Superellipse "squircle" corner generator.
//
// A plain CSS border-radius corner is a quarter-circle: |x/R|^2 + |y/R|^2 = 1.
// iOS-style "continuous curvature" corners are closer to a superellipse with a
// higher exponent: |x/R|^n + |y/R|^n = 1. Raising n makes the curve hug the
// straight edges longer before turning, then cut the corner more abruptly -
// the flatter, "squarer" look Apple's app icons are known for. n=2 is
// mathematically identical to a normal rounded corner; n≈5 is a commonly used
// approximation of Apple's icon curve.
//
// Each of the 4 corners is generated by sampling this quarter-superellipse in
// its own LOCAL frame (u, v both in [0, R], u=R at the start, v=R at the end)
// and then translating/reflecting it into place. The reflections differ per
// corner (see the exported *_POINT functions below) - each was independently
// derived and verified so that at n=2 every sampled point lands exactly R
// away from that corner's circular-arc center, matching a normal rounded rect.

export interface SquircleConfig {
  width: number;
  height: number;
  radius: number;
  smoothing: number; // 0-100
  steps?: number; // samples per 90° corner
}

const DEFAULT_STEPS = 28;
const MIN_EXPONENT = 2;
const MAX_EXPONENT = 8;

export function smoothingToExponent(smoothing: number): number {
  const clamped = Math.min(100, Math.max(0, smoothing));

  return MIN_EXPONENT + (clamped / 100) * (MAX_EXPONENT - MIN_EXPONENT);
}

function superU(theta: number, r: number, n: number): number {
  return r * Math.pow(Math.cos(theta), 2 / n);
}

function superV(theta: number, r: number, n: number): number {
  return r * Math.pow(Math.sin(theta), 2 / n);
}

function thetas(steps: number): number[] {
  return Array.from({ length: steps + 1 }, (_, i) => (i / steps) * (Math.PI / 2));
}

export interface Point {
  x: number;
  y: number;
}

export function clampRadius(width: number, height: number, radius: number): number {
  return Math.max(0, Math.min(radius, width / 2, height / 2));
}

export function topLeftCorner(w: number, h: number, r: number, n: number, steps: number): Point[] {
  return thetas(steps).map((t) => ({ x: r - superU(t, r, n), y: r - superV(t, r, n) }));
}

export function topRightCorner(w: number, h: number, r: number, n: number, steps: number): Point[] {
  return thetas(steps).map((t) => ({ x: w - r + superV(t, r, n), y: r - superU(t, r, n) }));
}

export function bottomRightCorner(w: number, h: number, r: number, n: number, steps: number): Point[] {
  return thetas(steps).map((t) => ({ x: w - r + superU(t, r, n), y: h - r + superV(t, r, n) }));
}

export function bottomLeftCorner(w: number, h: number, r: number, n: number, steps: number): Point[] {
  return thetas(steps).map((t) => ({ x: r - superV(t, r, n), y: h - r + superU(t, r, n) }));
}

export function generateSquirclePoints(config: SquircleConfig): Point[] {
  const steps = config.steps ?? DEFAULT_STEPS;
  const w = config.width;
  const h = config.height;
  const r = clampRadius(w, h, config.radius);
  const n = smoothingToExponent(config.smoothing);

  return [
    ...topLeftCorner(w, h, r, n, steps),
    ...topRightCorner(w, h, r, n, steps),
    ...bottomRightCorner(w, h, r, n, steps),
    ...bottomLeftCorner(w, h, r, n, steps),
  ];
}

function fmt(n: number): string {
  return Math.round(n * 100) / 100 + "";
}

export function pointsToSvgPath(points: Point[]): string {
  if (points.length === 0) return "";

  const [first, ...rest] = points;
  const lines = rest.map((p) => `L ${fmt(p.x)} ${fmt(p.y)}`).join(" ");

  return `M ${fmt(first.x)} ${fmt(first.y)} ${lines} Z`;
}

export function generateSquirclePath(config: SquircleConfig): string {
  return pointsToSvgPath(generateSquirclePoints(config));
}
